
function _MainCampaignLevel1(world)
	
-- Automatically generated world load file
-- Can be edited manually

world:createEmptyWorld(60, 20)

-- Grid begin
world.tileWidth = 60
world.tileHeight = 60
local h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[0][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[0][19] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[1][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[1][19] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[2][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[2][19] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[3][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[3][19] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[4][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[4][19] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood_oblique_left")
world.tiles[5][17] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[5][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[5][19] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood_oblique_left")
world.tiles[6][16] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("brick_bright")
world.tiles[6][17] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[6][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[6][19] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood_oblique_left")
world.tiles[7][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("brick_bright")
world.tiles[7][16] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("brick_bright")
world.tiles[7][17] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[7][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[7][19] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood_oblique_left")
world.tiles[8][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("brick_bright")
world.tiles[8][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("brick_bright")
world.tiles[8][16] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("brick_bright")
world.tiles[8][17] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[8][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[8][19] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("snow_secret")
world.tiles[9][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("snow_secret")
world.tiles[9][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("snow_secret")
world.tiles[9][16] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("snow_secret")
world.tiles[9][17] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[9][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[9][19] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("brick_bright_single_coin")
world.tiles[10][9] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("snow_secret")
world.tiles[10][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("snow_secret")
world.tiles[10][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("snow_secret")
world.tiles[10][16] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("snow_secret")
world.tiles[10][17] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[10][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[10][19] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("snow_secret")
world.tiles[11][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("snow_secret")
world.tiles[11][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("snow_secret")
world.tiles[11][16] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("snow_secret")
world.tiles[11][17] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[11][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[11][19] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("snow_secret")
world.tiles[12][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("snow_secret")
world.tiles[12][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("snow_secret")
world.tiles[12][16] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("snow_secret")
world.tiles[12][17] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[12][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[12][19] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("brick_bright_coins")
world.tiles[13][9] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("snow_secret")
world.tiles[13][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("snow_secret")
world.tiles[13][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("snow_secret")
world.tiles[13][16] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("snow_secret")
world.tiles[13][17] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[13][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[13][19] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("snow_secret")
world.tiles[14][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("snow_secret")
world.tiles[14][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("brick_bright")
world.tiles[14][16] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("brick_bright")
world.tiles[14][17] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[14][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[14][19] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("brick_bright")
world.tiles[15][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("brick_bright")
world.tiles[15][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("brick_bright")
world.tiles[15][16] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("brick_bright")
world.tiles[15][17] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[15][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[15][19] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood_oblique_right")
world.tiles[16][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("brick_bright")
world.tiles[16][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("brick_bright")
world.tiles[16][16] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("brick_bright")
world.tiles[16][17] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[16][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[16][19] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood_oblique_right")
world.tiles[17][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("brick_bright")
world.tiles[17][16] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("brick_bright")
world.tiles[17][17] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[17][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[17][19] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood_oblique_right")
world.tiles[18][16] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("brick_bright")
world.tiles[18][17] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[18][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[18][19] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood_oblique_right")
world.tiles[19][17] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[19][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[19][19] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[20][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[20][19] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[21][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[21][19] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[22][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[22][19] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[23][16] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[23][17] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[23][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[23][19] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("lava_top")
world.tiles[24][16] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("lava_inside")
world.tiles[24][17] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[24][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[24][19] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("lava_top")
world.tiles[25][16] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("lava_inside")
world.tiles[25][17] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[25][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[25][19] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("lava_top")
world.tiles[26][16] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("lava_inside")
world.tiles[26][17] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[26][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[26][19] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("lava_top")
world.tiles[27][16] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("lava_inside")
world.tiles[27][17] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[27][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[27][19] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("lava_top")
world.tiles[28][16] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("lava_inside")
world.tiles[28][17] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[28][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[28][19] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[29][16] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[29][17] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[29][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[29][19] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[30][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[30][19] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[31][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[31][19] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[32][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[32][19] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[33][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[33][19] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[34][16] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[34][17] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[34][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[34][19] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_top")
world.tiles[35][16] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[35][17] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[35][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[35][19] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_top")
world.tiles[36][16] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[36][17] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[36][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[36][19] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_top")
world.tiles[37][16] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[37][17] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[37][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[37][19] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_top")
world.tiles[38][16] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[38][17] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[38][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[38][19] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_top")
world.tiles[39][16] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[39][17] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[39][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[39][19] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[40][16] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[40][17] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[40][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[40][19] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[41][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[41][19] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[42][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[42][19] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[43][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[43][19] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_bright")
world.tiles[44][17] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[44][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[44][19] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[45][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[45][19] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[46][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[46][19] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[47][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[47][19] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[48][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[48][19] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[49][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[49][19] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[50][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[50][19] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_bright")
world.tiles[51][17] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[51][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[51][19] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_bright")
world.tiles[52][17] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[52][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[52][19] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[53][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[53][19] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[54][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[54][19] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[55][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[55][19] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[56][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[56][19] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[57][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[57][19] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[58][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[58][19] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[59][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[59][19] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
-- Grid end

-- Animation objects begin
world:fillObjectIntoGrid(createAnimationObjectFromName("torch", 20, 15, world.tileWidth,  world.tileHeight, world.textureContainer, world.animObjContainer), "backgroundObj")
world:fillObjectIntoGrid(createAnimationObjectFromName("torch", 22, 15, world.tileWidth,  world.tileHeight, world.textureContainer, world.animObjContainer), "backgroundObj")
world:fillObjectIntoGrid(createAnimationObjectFromName("tree_anim_2_3", 31, 15, world.tileWidth,  world.tileHeight, world.textureContainer, world.animObjContainer), "foregroundObj")
-- Animation objects end

-- Active objects begin
local acObj
acObj = createActiveObjectFromName("teleport", 42, 17, world.tileWidth, world.tileHeight, world.textureContainer, false, nil)
world:addActiveObject(acObj)
acObj = createActiveObjectFromName("teleport", 33, 17, world.tileWidth, world.tileHeight, world.textureContainer, false, nil)
world:addActiveObject(acObj)
acObj = createActiveObjectFromName("horizontal_platform_start", 8, 12, world.tileWidth, world.tileHeight, world.textureContainer, false, nil)
world:addActiveObject(acObj)
acObj = createActiveObjectFromName("trampoline", 21, 17, world.tileWidth, world.tileHeight, world.textureContainer, false, nil)
world:addActiveObject(acObj)
acObj = createActiveObjectFromName("vertical_platform_end", 45, 10, world.tileWidth, world.tileHeight, world.textureContainer, false, nil)
world:addActiveObject(acObj)
acObj = createActiveObjectFromName("vertical_platform_start", 48, 10, world.tileWidth, world.tileHeight, world.textureContainer, false, nil)
world:addActiveObject(acObj)
acObj = createActiveObjectFromName("canon", 51, 16, world.tileWidth, world.tileHeight, world.textureContainer, true, 3)
world:addActiveObject(acObj)
world:connectTeleports(42, 17, 33, 17)
world:connectTeleports(33, 17, 42, 17)
-- Active objects end

-- Units begin
local unit
unit = createUnitFromName("spiky", 2790, 1050, world.tileWidth, world.tileHeight, world.textureContainer, true)
world:addUnit(unit)
unit = createUnitFromName("spiky", 2970, 1050, world.tileWidth, world.tileHeight, world.textureContainer, true)
world:addUnit(unit)
unit = createUnitFromName("coin", 2187, 807, world.tileWidth, world.tileHeight, world.textureContainer, true)
world:addUnit(unit)
unit = createUnitFromName("coin", 2307, 807, world.tileWidth, world.tileHeight, world.textureContainer, true)
world:addUnit(unit)
unit = createUnitFromName("turtle", 270, 1050, world.tileWidth, world.tileHeight, world.textureContainer, true)
world:addUnit(unit)
-- Units end

-- Parallax background begin
-- Background begin: 1
world:setCameraVelocityParallaxBackground(1, 0)
-- Background end
-- Background begin: 2
world:setCameraVelocityParallaxBackground(2, 0)
-- Background end
-- Background begin: 3
world:setCameraVelocityParallaxBackground(3, 0)
-- Background end
-- Background begin: 4
world:setCameraVelocityParallaxBackground(4, 0)
-- Background end
-- Parallax background end

-- Player spawn position begin
world.playerSpawnX = 90
world.playerSpawnY = 90
-- Player spawn position end

-- Player finish line begin
world.playerFinishLine = 3450
-- Player finish line end

-- Background music begin
-- Background music end


end