
-- Automatically generated world load file
-- Can be edited manually

local world = ...
world:createEmptyWorld(200, 16)

-- Grid begin
world.tileWidth = 60
world.tileHeight = 60
local h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wall")
world.tiles[0][12] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[0][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[0][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[0][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wall")
world.tiles[1][12] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[1][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[1][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[1][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wall")
world.tiles[2][12] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[2][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[2][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[2][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wall")
world.tiles[3][12] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[3][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[3][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[3][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wall")
world.tiles[4][12] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[4][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[4][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[4][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wall")
world.tiles[5][12] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[5][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[5][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[5][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wall")
world.tiles[6][12] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[6][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[6][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[6][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wall")
world.tiles[7][12] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[7][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[7][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[7][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wall")
world.tiles[8][12] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[8][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[8][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[8][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wall")
world.tiles[9][12] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[9][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[9][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[9][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wall")
world.tiles[10][12] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[10][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[10][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[10][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wall_oblique_right")
world.tiles[11][12] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top_right")
world.tiles[11][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[11][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[11][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[12][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[12][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[12][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[13][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[13][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[13][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("surprise_mushroom_life")
world.tiles[14][10] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[14][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[14][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[14][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("surprise_coin")
world.tiles[15][10] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[15][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[15][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[15][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[16][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[16][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[16][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[17][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[17][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[17][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[18][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[18][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[18][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[19][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[19][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[19][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[20][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[20][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[20][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[21][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[21][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[21][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[22][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[22][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[22][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[23][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[23][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[23][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[24][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[24][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[24][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[25][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[25][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[25][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[26][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[26][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[26][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[27][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[27][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[27][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[28][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[28][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[28][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[29][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[29][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[29][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[30][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[30][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[30][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[31][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[31][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[31][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[32][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[32][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[32][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[33][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[33][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[33][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[34][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[34][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[34][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[35][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[35][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[35][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[36][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[36][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[36][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[37][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[37][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[37][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[38][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[38][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[38][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[39][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[39][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[39][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[40][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[40][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[40][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[41][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[41][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[41][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[42][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[42][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[42][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[43][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[43][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[43][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[44][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[44][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[44][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[45][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[45][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[45][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[46][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[46][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[46][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[47][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[47][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[47][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[48][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[48][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[48][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[49][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[49][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[49][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[50][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[50][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[50][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[51][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[51][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[51][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[52][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[52][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[52][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[53][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[53][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[53][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[54][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[54][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[54][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[55][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[55][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[55][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[56][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[56][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[56][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[57][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[57][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[57][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[58][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[58][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[58][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[59][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[59][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[59][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[60][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[60][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[60][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[61][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[61][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[61][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top_left")
world.tiles[62][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[62][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[62][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("surprise_mushroom_grow")
world.tiles[64][6] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("block")
world.tiles[64][10] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("block")
world.tiles[64][11] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("block")
world.tiles[64][12] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top_right")
world.tiles[64][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[64][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[64][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[65][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[65][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[65][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[66][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[66][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[66][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[67][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[67][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[67][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[68][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[68][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[68][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[69][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[69][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[69][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[70][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[70][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[70][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[71][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[71][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[71][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[72][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[72][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[72][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[73][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[73][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[73][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[74][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[74][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[74][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[75][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[75][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[75][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[76][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[76][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[76][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[77][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[77][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[77][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[78][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[78][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[78][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[79][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[79][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[79][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[80][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[80][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[80][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[81][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[81][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[81][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[82][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[82][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[82][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top_left")
world.tiles[83][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[83][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[83][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top_right")
world.tiles[88][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[88][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[88][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[89][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[89][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[89][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[90][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[90][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[90][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[91][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[91][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[91][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[92][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[92][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[92][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[93][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[93][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[93][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[94][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[94][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[94][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[95][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[95][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[95][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[96][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[96][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[96][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[97][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[97][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[97][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[98][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[98][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[98][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[99][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[99][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[99][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[100][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[100][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[100][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[101][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[101][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[101][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("block")
world.tiles[102][12] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[102][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[102][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[102][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("block")
world.tiles[103][11] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("block")
world.tiles[103][12] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[103][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[103][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[103][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("block")
world.tiles[104][10] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("block")
world.tiles[104][11] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("block")
world.tiles[104][12] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[104][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[104][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[104][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("block")
world.tiles[105][11] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("block")
world.tiles[105][12] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[105][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[105][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[105][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("block")
world.tiles[106][12] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top_left")
world.tiles[106][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[106][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[106][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("surprise_mushroom_grow")
world.tiles[107][9] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_oblique_right")
world.tiles[107][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[107][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[107][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_oblique_right")
world.tiles[108][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[108][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_oblique_right")
world.tiles[109][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_oblique_left")
world.tiles[113][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_oblique_left")
world.tiles[114][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[114][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_oblique_left")
world.tiles[115][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[115][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[115][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top_right")
world.tiles[116][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[116][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[116][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[117][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[117][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[117][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[118][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[118][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[118][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[119][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[119][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[119][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[120][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[120][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[120][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[121][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[121][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[121][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[122][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[122][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[122][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[123][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[123][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[123][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[124][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[124][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[124][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[125][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[125][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[125][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[126][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[126][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[126][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[127][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[127][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[127][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[128][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[128][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[128][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[129][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[129][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[129][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[130][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[130][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[130][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[131][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[131][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[131][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("block")
world.tiles[132][12] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[132][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[132][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[132][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("block")
world.tiles[133][12] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[133][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[133][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[133][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("block")
world.tiles[134][12] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[134][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[134][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[134][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[135][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[135][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[135][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[136][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[136][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[136][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[137][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[137][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[137][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[138][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[138][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[138][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[139][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[139][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[139][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[140][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[140][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[140][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[141][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[141][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[141][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_funny_left")
world.tiles[142][1] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[142][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[142][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[142][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_funny_mid")
world.tiles[143][1] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_oblique_right")
world.tiles[143][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[143][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[143][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_funny_mid")
world.tiles[144][1] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_oblique_right")
world.tiles[144][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top_right")
world.tiles[144][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_funny_mid")
world.tiles[145][1] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[145][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_funny_mid")
world.tiles[146][1] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[146][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_funny_mid")
world.tiles[147][1] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[147][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_funny_mid")
world.tiles[148][1] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h2 = world.headerContainer:getHeader("timber")
world.tiles[148][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[148][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_funny_mid")
world.tiles[149][1] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[149][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_funny_mid")
world.tiles[150][1] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[150][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_funny_mid")
world.tiles[151][1] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[151][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_funny_mid")
world.tiles[152][1] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[152][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_funny_mid")
world.tiles[153][1] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[153][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_funny_mid")
world.tiles[154][1] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[154][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_funny_mid")
world.tiles[155][1] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[155][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_funny_mid")
world.tiles[156][1] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top")
world.tiles[156][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_funny_mid")
world.tiles[157][1] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_oblique_left")
world.tiles[157][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_top_left")
world.tiles[157][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_funny_mid")
world.tiles[158][1] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_oblique_left")
world.tiles[158][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[158][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[158][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_funny_mid")
world.tiles[159][1] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wall_oblique_left")
world.tiles[159][12] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[159][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[159][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[159][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_funny_mid")
world.tiles[160][1] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wall")
world.tiles[160][12] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[160][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[160][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[160][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("grass_funny_right")
world.tiles[161][1] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wall")
world.tiles[161][12] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[161][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[161][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[161][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wall")
world.tiles[162][12] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[162][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[162][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[162][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wall")
world.tiles[163][12] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[163][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[163][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[163][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wall")
world.tiles[164][12] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[164][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[164][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[164][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wall")
world.tiles[165][12] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[165][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[165][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[165][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h2 = world.headerContainer:getHeader("wall")
world.tiles[166][10] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h2 = world.headerContainer:getHeader("wall")
world.tiles[166][11] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wall")
world.tiles[166][12] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[166][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[166][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[166][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wall")
world.tiles[167][12] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[167][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[167][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[167][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wall")
world.tiles[168][12] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[168][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[168][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[168][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wall")
world.tiles[169][12] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[169][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[169][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[169][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wall")
world.tiles[170][12] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[170][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[170][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[170][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wall")
world.tiles[171][12] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[171][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[171][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[171][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wall")
world.tiles[172][12] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[172][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[172][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[172][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h2 = world.headerContainer:getHeader("wall")
world.tiles[173][10] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h2 = world.headerContainer:getHeader("wall")
world.tiles[173][11] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wall")
world.tiles[173][12] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[173][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[173][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[173][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wall")
world.tiles[174][12] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[174][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[174][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[174][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wall")
world.tiles[175][12] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[175][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[175][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[175][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wall")
world.tiles[176][12] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[176][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[176][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[176][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wall")
world.tiles[177][12] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[177][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[177][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[177][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wall")
world.tiles[178][12] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[178][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[178][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[178][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wall")
world.tiles[179][12] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[179][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[179][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[179][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h2 = world.headerContainer:getHeader("wall")
world.tiles[180][10] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h2 = world.headerContainer:getHeader("wall")
world.tiles[180][11] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wall")
world.tiles[180][12] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[180][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[180][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[180][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wall")
world.tiles[181][12] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[181][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[181][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[181][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wall")
world.tiles[182][12] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[182][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[182][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[182][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wall")
world.tiles[183][12] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[183][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[183][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[183][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wall")
world.tiles[184][12] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[184][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[184][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[184][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wall")
world.tiles[185][12] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[185][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[185][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[185][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wall")
world.tiles[186][12] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[186][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[186][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[186][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h2 = world.headerContainer:getHeader("wall")
world.tiles[187][10] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h2 = world.headerContainer:getHeader("wall")
world.tiles[187][11] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wall")
world.tiles[187][12] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[187][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[187][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[187][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wall")
world.tiles[188][12] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[188][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[188][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[188][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wall")
world.tiles[189][12] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[189][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[189][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[189][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wall")
world.tiles[190][12] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[190][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[190][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[190][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wall")
world.tiles[191][12] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[191][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[191][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[191][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h2 = world.headerContainer:getHeader("finish_line")
world.tiles[192][4] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h2 = world.headerContainer:getHeader("finish_line")
world.tiles[192][5] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h2 = world.headerContainer:getHeader("finish_line")
world.tiles[192][6] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h2 = world.headerContainer:getHeader("finish_line")
world.tiles[192][7] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h2 = world.headerContainer:getHeader("finish_line")
world.tiles[192][8] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h2 = world.headerContainer:getHeader("finish_line")
world.tiles[192][9] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h2 = world.headerContainer:getHeader("finish_line")
world.tiles[192][10] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h2 = world.headerContainer:getHeader("finish_line")
world.tiles[192][11] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wall")
world.tiles[192][12] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[192][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[192][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[192][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wall")
world.tiles[193][12] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[193][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[193][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[193][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wall")
world.tiles[194][12] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[194][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[194][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[194][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wall")
world.tiles[195][12] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[195][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[195][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[195][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wall")
world.tiles[196][12] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[196][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[196][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[196][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wall")
world.tiles[197][12] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[197][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[197][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[197][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wall")
world.tiles[198][12] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[198][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[198][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[198][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wall")
world.tiles[199][12] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[199][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[199][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("mud_mid")
world.tiles[199][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
-- Grid end

-- Animation objects begin
world:fillObjectIntoGrid(createAnimationObjectFromName("streetlamp", 2, 9, world.tileWidth,  world.tileHeight, world.textureContainer, world.animObjContainer), "backgroundObj")
world:fillObjectIntoGrid(createAnimationObjectFromName("streetlamp", 7, 9, world.tileWidth,  world.tileHeight, world.textureContainer, world.animObjContainer), "backgroundObj")
world:fillObjectIntoGrid(createAnimationObjectFromName("rock", 13, 12, world.tileWidth,  world.tileHeight, world.textureContainer, world.animObjContainer), "foregroundObj")
world:fillObjectIntoGrid(createAnimationObjectFromName("tree_3", 15, 9, world.tileWidth,  world.tileHeight, world.textureContainer, world.animObjContainer), "backgroundObj")
world:fillObjectIntoGrid(createAnimationObjectFromName("tree_3", 18, 9, world.tileWidth,  world.tileHeight, world.textureContainer, world.animObjContainer), "backgroundObj")
world:fillObjectIntoGrid(createAnimationObjectFromName("tree_3", 21, 9, world.tileWidth,  world.tileHeight, world.textureContainer, world.animObjContainer), "backgroundObj")
world:fillObjectIntoGrid(createAnimationObjectFromName("tree_3", 24, 9, world.tileWidth,  world.tileHeight, world.textureContainer, world.animObjContainer), "backgroundObj")
world:fillObjectIntoGrid(createAnimationObjectFromName("tree_3", 27, 9, world.tileWidth,  world.tileHeight, world.textureContainer, world.animObjContainer), "foregroundObj")
world:fillObjectIntoGrid(createAnimationObjectFromName("tree_3", 30, 9, world.tileWidth,  world.tileHeight, world.textureContainer, world.animObjContainer), "foregroundObj")
world:fillObjectIntoGrid(createAnimationObjectFromName("tree_3", 33, 9, world.tileWidth,  world.tileHeight, world.textureContainer, world.animObjContainer), "backgroundObj")
world:fillObjectIntoGrid(createAnimationObjectFromName("tree_3", 36, 9, world.tileWidth,  world.tileHeight, world.textureContainer, world.animObjContainer), "backgroundObj")
world:fillObjectIntoGrid(createAnimationObjectFromName("tree_3", 39, 9, world.tileWidth,  world.tileHeight, world.textureContainer, world.animObjContainer), "backgroundObj")
world:fillObjectIntoGrid(createAnimationObjectFromName("tree_3", 42, 9, world.tileWidth,  world.tileHeight, world.textureContainer, world.animObjContainer), "foregroundObj")
world:fillObjectIntoGrid(createAnimationObjectFromName("tree_3", 45, 9, world.tileWidth,  world.tileHeight, world.textureContainer, world.animObjContainer), "backgroundObj")
world:fillObjectIntoGrid(createAnimationObjectFromName("tree_3", 48, 9, world.tileWidth,  world.tileHeight, world.textureContainer, world.animObjContainer), "foregroundObj")
world:fillObjectIntoGrid(createAnimationObjectFromName("tree_3", 51, 9, world.tileWidth,  world.tileHeight, world.textureContainer, world.animObjContainer), "foregroundObj")
world:fillObjectIntoGrid(createAnimationObjectFromName("tree_3", 54, 9, world.tileWidth,  world.tileHeight, world.textureContainer, world.animObjContainer), "foregroundObj")
world:fillObjectIntoGrid(createAnimationObjectFromName("tree_3", 57, 9, world.tileWidth,  world.tileHeight, world.textureContainer, world.animObjContainer), "foregroundObj")
world:fillObjectIntoGrid(createAnimationObjectFromName("tree_3", 60, 9, world.tileWidth,  world.tileHeight, world.textureContainer, world.animObjContainer), "backgroundObj")
world:fillObjectIntoGrid(createAnimationObjectFromName("tree_3", 64, 9, world.tileWidth,  world.tileHeight, world.textureContainer, world.animObjContainer), "backgroundObj")
world:fillObjectIntoGrid(createAnimationObjectFromName("tree_3", 67, 9, world.tileWidth,  world.tileHeight, world.textureContainer, world.animObjContainer), "backgroundObj")
world:fillObjectIntoGrid(createAnimationObjectFromName("tree_3", 71, 9, world.tileWidth,  world.tileHeight, world.textureContainer, world.animObjContainer), "backgroundObj")
world:fillObjectIntoGrid(createAnimationObjectFromName("tree_3", 75, 9, world.tileWidth,  world.tileHeight, world.textureContainer, world.animObjContainer), "foregroundObj")
world:fillObjectIntoGrid(createAnimationObjectFromName("tree_3", 78, 9, world.tileWidth,  world.tileHeight, world.textureContainer, world.animObjContainer), "foregroundObj")
world:fillObjectIntoGrid(createAnimationObjectFromName("tree_3", 81, 9, world.tileWidth,  world.tileHeight, world.textureContainer, world.animObjContainer), "foregroundObj")
world:fillObjectIntoGrid(createAnimationObjectFromName("tree_3", 88, 9, world.tileWidth,  world.tileHeight, world.textureContainer, world.animObjContainer), "backgroundObj")
world:fillObjectIntoGrid(createAnimationObjectFromName("tree_3", 91, 9, world.tileWidth,  world.tileHeight, world.textureContainer, world.animObjContainer), "foregroundObj")
world:fillObjectIntoGrid(createAnimationObjectFromName("tree_3", 94, 9, world.tileWidth,  world.tileHeight, world.textureContainer, world.animObjContainer), "backgroundObj")
world:fillObjectIntoGrid(createAnimationObjectFromName("tree_3", 97, 9, world.tileWidth,  world.tileHeight, world.textureContainer, world.animObjContainer), "backgroundObj")
world:fillObjectIntoGrid(createAnimationObjectFromName("tree_3", 101, 9, world.tileWidth,  world.tileHeight, world.textureContainer, world.animObjContainer), "backgroundObj")
world:fillObjectIntoGrid(createAnimationObjectFromName("bush_2", 117, 12, world.tileWidth,  world.tileHeight, world.textureContainer, world.animObjContainer), "foregroundObj")
world:fillObjectIntoGrid(createAnimationObjectFromName("tree_3", 120, 9, world.tileWidth,  world.tileHeight, world.textureContainer, world.animObjContainer), "backgroundObj")
world:fillObjectIntoGrid(createAnimationObjectFromName("tree_3", 124, 9, world.tileWidth,  world.tileHeight, world.textureContainer, world.animObjContainer), "backgroundObj")
world:fillObjectIntoGrid(createAnimationObjectFromName("tree_3", 128, 9, world.tileWidth,  world.tileHeight, world.textureContainer, world.animObjContainer), "backgroundObj")
world:fillObjectIntoGrid(createAnimationObjectFromName("tree_1", 136, 9, world.tileWidth,  world.tileHeight, world.textureContainer, world.animObjContainer), "foregroundObj")
world:fillObjectIntoGrid(createAnimationObjectFromName("tree_3", 139, 9, world.tileWidth,  world.tileHeight, world.textureContainer, world.animObjContainer), "backgroundObj")
world:fillObjectIntoGrid(createAnimationObjectFromName("fire", 148, 14, world.tileWidth,  world.tileHeight, world.textureContainer, world.animObjContainer), "backgroundObj")
world:fillObjectIntoGrid(createAnimationObjectFromName("streetlamp", 162, 9, world.tileWidth,  world.tileHeight, world.textureContainer, world.animObjContainer), "backgroundObj")
world:fillObjectIntoGrid(createAnimationObjectFromName("fire", 166, 9, world.tileWidth,  world.tileHeight, world.textureContainer, world.animObjContainer), "backgroundObj")
world:fillObjectIntoGrid(createAnimationObjectFromName("streetlamp", 169, 9, world.tileWidth,  world.tileHeight, world.textureContainer, world.animObjContainer), "backgroundObj")
world:fillObjectIntoGrid(createAnimationObjectFromName("fire", 173, 9, world.tileWidth,  world.tileHeight, world.textureContainer, world.animObjContainer), "backgroundObj")
world:fillObjectIntoGrid(createAnimationObjectFromName("streetlamp", 176, 9, world.tileWidth,  world.tileHeight, world.textureContainer, world.animObjContainer), "backgroundObj")
world:fillObjectIntoGrid(createAnimationObjectFromName("fire", 180, 9, world.tileWidth,  world.tileHeight, world.textureContainer, world.animObjContainer), "backgroundObj")
world:fillObjectIntoGrid(createAnimationObjectFromName("streetlamp", 183, 9, world.tileWidth,  world.tileHeight, world.textureContainer, world.animObjContainer), "backgroundObj")
world:fillObjectIntoGrid(createAnimationObjectFromName("fire", 187, 9, world.tileWidth,  world.tileHeight, world.textureContainer, world.animObjContainer), "backgroundObj")
world:fillObjectIntoGrid(createAnimationObjectFromName("finish_line", 190, 4, world.tileWidth,  world.tileHeight, world.textureContainer, world.animObjContainer), "foregroundObj")
world:fillObjectIntoGrid(createAnimationObjectFromName("finish_line", 190, 5, world.tileWidth,  world.tileHeight, world.textureContainer, world.animObjContainer), "foregroundObj")
world:fillObjectIntoGrid(createAnimationObjectFromName("finish_line", 190, 6, world.tileWidth,  world.tileHeight, world.textureContainer, world.animObjContainer), "foregroundObj")
world:fillObjectIntoGrid(createAnimationObjectFromName("finish_line", 190, 7, world.tileWidth,  world.tileHeight, world.textureContainer, world.animObjContainer), "foregroundObj")
world:fillObjectIntoGrid(createAnimationObjectFromName("finish_line", 190, 8, world.tileWidth,  world.tileHeight, world.textureContainer, world.animObjContainer), "foregroundObj")
world:fillObjectIntoGrid(createAnimationObjectFromName("finish_line", 190, 9, world.tileWidth,  world.tileHeight, world.textureContainer, world.animObjContainer), "foregroundObj")
world:fillObjectIntoGrid(createAnimationObjectFromName("finish_line", 190, 10, world.tileWidth,  world.tileHeight, world.textureContainer, world.animObjContainer), "foregroundObj")
world:fillObjectIntoGrid(createAnimationObjectFromName("finish_line", 190, 11, world.tileWidth,  world.tileHeight, world.textureContainer, world.animObjContainer), "foregroundObj")
world:fillObjectIntoGrid(createAnimationObjectFromName("streetlamp", 195, 9, world.tileWidth,  world.tileHeight, world.textureContainer, world.animObjContainer), "backgroundObj")
-- Animation objects end

-- Active objects begin
local acObj
acObj = createActiveObjectFromName("canon", 100, 12, world.tileWidth, world.tileHeight, world.textureContainer, true, nil)
world:addActiveObject(acObj)
acObj = createActiveObjectFromName("canon", 101, 11, world.tileWidth, world.tileHeight, world.textureContainer, true, nil)
world:addActiveObject(acObj)
acObj = createActiveObjectFromName("canon", 102, 10, world.tileWidth, world.tileHeight, world.textureContainer, true, nil)
world:addActiveObject(acObj)
acObj = createActiveObjectFromName("teleport", 133, 11, world.tileWidth, world.tileHeight, world.textureContainer, false, nil)
world:addActiveObject(acObj)
acObj = createActiveObjectFromName("teleport", 143, 0, world.tileWidth, world.tileHeight, world.textureContainer, false, nil)
world:addActiveObject(acObj)
acObj = createActiveObjectFromName("smoke_source", 148, 13, world.tileWidth, world.tileHeight, world.textureContainer, false, nil)
world:addActiveObject(acObj)
acObj = createActiveObjectFromName("smoke_source", 180, 8, world.tileWidth, world.tileHeight, world.textureContainer, false, nil)
world:addActiveObject(acObj)
acObj = createActiveObjectFromName("smoke_source", 166, 8, world.tileWidth, world.tileHeight, world.textureContainer, false, nil)
world:addActiveObject(acObj)
acObj = createActiveObjectFromName("smoke_source", 173, 8, world.tileWidth, world.tileHeight, world.textureContainer, false, nil)
world:addActiveObject(acObj)
acObj = createActiveObjectFromName("smoke_source", 187, 8, world.tileWidth, world.tileHeight, world.textureContainer, false, nil)
world:addActiveObject(acObj)
world:connectTeleports(133, 11, 143, 0)
world:connectTeleports(143, 0, 133, 11)
-- Active objects end

-- Units begin
local unit
unit = createUnitFromName("spiky", 7710, 750, world.tileWidth, world.tileHeight, world.textureContainer, true)
world:addUnit(unit)
unit = createUnitFromName("spiky", 7830, 750, world.tileWidth, world.tileHeight, world.textureContainer, true)
world:addUnit(unit)
unit = createUnitFromName("bouncing_zombie", 8310, 750, world.tileWidth, world.tileHeight, world.textureContainer, true)
world:addUnit(unit)
unit = createUnitFromName("bouncing_zombie", 8430, 750, world.tileWidth, world.tileHeight, world.textureContainer, true)
world:addUnit(unit)
unit = createUnitFromName("coin", 8727, 27, world.tileWidth, world.tileHeight, world.textureContainer, false)
world:addUnit(unit)
unit = createUnitFromName("coin", 8787, 27, world.tileWidth, world.tileHeight, world.textureContainer, false)
world:addUnit(unit)
unit = createUnitFromName("coin", 8847, 27, world.tileWidth, world.tileHeight, world.textureContainer, false)
world:addUnit(unit)
unit = createUnitFromName("coin", 8907, 27, world.tileWidth, world.tileHeight, world.textureContainer, false)
world:addUnit(unit)
unit = createUnitFromName("coin", 8967, 27, world.tileWidth, world.tileHeight, world.textureContainer, false)
world:addUnit(unit)
unit = createUnitFromName("coin", 9027, 27, world.tileWidth, world.tileHeight, world.textureContainer, false)
world:addUnit(unit)
unit = createUnitFromName("coin", 9087, 27, world.tileWidth, world.tileHeight, world.textureContainer, false)
world:addUnit(unit)
unit = createUnitFromName("coin", 9147, 27, world.tileWidth, world.tileHeight, world.textureContainer, false)
world:addUnit(unit)
unit = createUnitFromName("jumper", 9150, 870, world.tileWidth, world.tileHeight, world.textureContainer, true)
world:addUnit(unit)
unit = createUnitFromName("coin", 9207, 27, world.tileWidth, world.tileHeight, world.textureContainer, false)
world:addUnit(unit)
unit = createUnitFromName("coin", 9267, 27, world.tileWidth, world.tileHeight, world.textureContainer, false)
world:addUnit(unit)
unit = createUnitFromName("jumper", 9270, 870, world.tileWidth, world.tileHeight, world.textureContainer, true)
world:addUnit(unit)
unit = createUnitFromName("coin", 9327, 27, world.tileWidth, world.tileHeight, world.textureContainer, false)
world:addUnit(unit)
unit = createUnitFromName("coin", 9387, 27, world.tileWidth, world.tileHeight, world.textureContainer, false)
world:addUnit(unit)
unit = createUnitFromName("jumper", 9390, 870, world.tileWidth, world.tileHeight, world.textureContainer, true)
world:addUnit(unit)
unit = createUnitFromName("coin", 9447, 27, world.tileWidth, world.tileHeight, world.textureContainer, false)
world:addUnit(unit)
unit = createUnitFromName("coin", 9507, 27, world.tileWidth, world.tileHeight, world.textureContainer, false)
world:addUnit(unit)
unit = createUnitFromName("coin", 9567, 27, world.tileWidth, world.tileHeight, world.textureContainer, false)
world:addUnit(unit)
unit = createUnitFromName("fireflower", 9627, 27, world.tileWidth, world.tileHeight, world.textureContainer, true)
world:addUnit(unit)
unit = createUnitFromName("rotating_ghost", 9975, 615, world.tileWidth, world.tileHeight, world.textureContainer, true)
world:addUnit(unit)
unit = createUnitFromName("rotating_ghost", 10395, 615, world.tileWidth, world.tileHeight, world.textureContainer, true)
world:addUnit(unit)
unit = createUnitFromName("rotating_ghost", 10815, 615, world.tileWidth, world.tileHeight, world.textureContainer, true)
world:addUnit(unit)
unit = createUnitFromName("rotating_ghost", 11235, 615, world.tileWidth, world.tileHeight, world.textureContainer, true)
world:addUnit(unit)
unit = createUnitFromName("spiky", 1710, 750, world.tileWidth, world.tileHeight, world.textureContainer, true)
world:addUnit(unit)
unit = createUnitFromName("spiky", 1830, 750, world.tileWidth, world.tileHeight, world.textureContainer, true)
world:addUnit(unit)
unit = createUnitFromName("spiky", 1950, 750, world.tileWidth, world.tileHeight, world.textureContainer, true)
world:addUnit(unit)
unit = createUnitFromName("spiky", 2070, 750, world.tileWidth, world.tileHeight, world.textureContainer, true)
world:addUnit(unit)
unit = createUnitFromName("zombie", 2310, 750, world.tileWidth, world.tileHeight, world.textureContainer, true)
world:addUnit(unit)
unit = createUnitFromName("zombie", 2430, 750, world.tileWidth, world.tileHeight, world.textureContainer, true)
world:addUnit(unit)
unit = createUnitFromName("zombie", 2550, 750, world.tileWidth, world.tileHeight, world.textureContainer, true)
world:addUnit(unit)
unit = createUnitFromName("zombie", 2670, 750, world.tileWidth, world.tileHeight, world.textureContainer, true)
world:addUnit(unit)
unit = createUnitFromName("zombie", 2790, 750, world.tileWidth, world.tileHeight, world.textureContainer, true)
world:addUnit(unit)
unit = createUnitFromName("bomberman", 2970, 750, world.tileWidth, world.tileHeight, world.textureContainer, true)
world:addUnit(unit)
unit = createUnitFromName("bomberman", 3090, 750, world.tileWidth, world.tileHeight, world.textureContainer, true)
world:addUnit(unit)
unit = createUnitFromName("bomberman", 3210, 750, world.tileWidth, world.tileHeight, world.textureContainer, true)
world:addUnit(unit)
unit = createUnitFromName("bomberman", 3330, 750, world.tileWidth, world.tileHeight, world.textureContainer, true)
world:addUnit(unit)
unit = createUnitFromName("bomberman", 3450, 750, world.tileWidth, world.tileHeight, world.textureContainer, true)
world:addUnit(unit)
unit = createUnitFromName("bomberman", 3630, 750, world.tileWidth, world.tileHeight, world.textureContainer, true)
world:addUnit(unit)
unit = createUnitFromName("coin", 3927, 627, world.tileWidth, world.tileHeight, world.textureContainer, false)
world:addUnit(unit)
unit = createUnitFromName("coin", 3987, 627, world.tileWidth, world.tileHeight, world.textureContainer, false)
world:addUnit(unit)
unit = createUnitFromName("coin", 4047, 627, world.tileWidth, world.tileHeight, world.textureContainer, false)
world:addUnit(unit)
unit = createUnitFromName("coin", 4107, 627, world.tileWidth, world.tileHeight, world.textureContainer, false)
world:addUnit(unit)
unit = createUnitFromName("coin", 4167, 627, world.tileWidth, world.tileHeight, world.textureContainer, false)
world:addUnit(unit)
unit = createUnitFromName("coin", 4167, 747, world.tileWidth, world.tileHeight, world.textureContainer, false)
world:addUnit(unit)
unit = createUnitFromName("coin", 4167, 507, world.tileWidth, world.tileHeight, world.textureContainer, false)
world:addUnit(unit)
unit = createUnitFromName("coin", 4227, 627, world.tileWidth, world.tileHeight, world.textureContainer, false)
world:addUnit(unit)
unit = createUnitFromName("coin", 4227, 687, world.tileWidth, world.tileHeight, world.textureContainer, false)
world:addUnit(unit)
unit = createUnitFromName("coin", 4227, 567, world.tileWidth, world.tileHeight, world.textureContainer, false)
world:addUnit(unit)
unit = createUnitFromName("coin", 4287, 627, world.tileWidth, world.tileHeight, world.textureContainer, false)
world:addUnit(unit)
unit = createUnitFromName("hammerman", 7050, 750, world.tileWidth, world.tileHeight, world.textureContainer, true)
world:addUnit(unit)
unit = createUnitFromName("spiky", 7590, 750, world.tileWidth, world.tileHeight, world.textureContainer, true)
world:addUnit(unit)
-- Units end

-- Parallax background begin
-- Background begin: 1
world:setBackgroundTexture(1, "bg_night")
world:setCameraVelocityParallaxBackground(1, "vertical", 0)
world:setCameraVelocityParallaxBackground(1, "horizontal", 0)
-- Background end
-- Background begin: 2
world:setBackgroundTexture(2, "bg_forest")
world:enableWeather(2, "Clouds", nil, 20)
world:setCameraVelocityParallaxBackground(2, "vertical", 0.05)
world:setCameraVelocityParallaxBackground(2, "horizontal", 0.12)
-- Background end
-- Background begin: 3
world:setBackgroundTexture(3, "bg_mud")
world:enableWeather(3, "Clouds", nil, 20)
world:setCameraVelocityParallaxBackground(3, "vertical", 0.11)
world:setCameraVelocityParallaxBackground(3, "horizontal", 0.35)
-- Background end
-- Background begin: 4
world:enableWeather(4, "Rain", true)
world:setCameraVelocityParallaxBackground(4, "vertical", 0.8)
world:setCameraVelocityParallaxBackground(4, "horizontal", 0.8)
-- Background end
-- Parallax background end

-- Player spawn position begin
world.playerSpawnX = 90
world.playerSpawnY = 690
-- Player spawn position end

-- Player finish line begin
world.playerFinishLine = 11490
-- Player finish line end

-- Background music begin
world:setBackgroundMusic("night")
-- Background music end

