
-- Automatically generated world load function
-- Can be edited manually

LoadWorldFunc = function(world)
world:createEmptyWorld(150, 25)

-- Grid begin
world.tileWidth = 60
world.tileHeight = 60
local h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("brick_dark")
world.tiles[0][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_bright")
world.tiles[0][17] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[0][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_bright")
world.tiles[1][17] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[1][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("snow")
world.tiles[2][10] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wooden_platform")
world.tiles[2][17] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[2][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wooden_platform")
world.tiles[3][17] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[3][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wooden_platform")
world.tiles[4][17] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[4][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("snow_oblique_left")
world.tiles[5][19] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[5][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("snow")
world.tiles[6][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("snow")
world.tiles[6][19] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[6][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("snow_oblique_right")
world.tiles[7][19] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[7][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("snow_oblique_left")
world.tiles[8][19] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[8][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("snow_oblique_left")
world.tiles[9][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("snow")
world.tiles[9][19] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[9][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("brick_bright")
world.tiles[10][16] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("snow_oblique_right")
world.tiles[10][19] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[10][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("brick_dark")
world.tiles[11][16] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[11][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[12][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("snow_oblique_left")
world.tiles[13][19] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[13][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("snow_oblique_left")
world.tiles[14][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("snow")
world.tiles[14][19] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[14][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("snow_oblique_left")
world.tiles[15][17] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("snow")
world.tiles[15][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("snow")
world.tiles[15][19] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[15][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("snow_oblique_left")
world.tiles[16][16] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("snow")
world.tiles[16][17] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("snow")
world.tiles[16][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("snow")
world.tiles[16][19] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[16][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("snow_oblique_right")
world.tiles[17][16] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("snow")
world.tiles[17][17] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("snow")
world.tiles[17][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("snow")
world.tiles[17][19] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[17][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("snow_oblique_right")
world.tiles[18][17] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("snow")
world.tiles[18][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("snow")
world.tiles[18][19] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[18][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("snow_oblique_right")
world.tiles[19][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("snow")
world.tiles[19][19] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[19][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("snow_oblique_right")
world.tiles[20][19] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[20][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[21][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[22][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[23][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[24][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("snow")
world.tiles[25][19] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[25][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[26][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[27][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[28][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[29][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[30][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[31][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[32][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[33][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[34][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[35][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("lava_top")
world.tiles[36][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("lava_inside")
world.tiles[36][19] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[36][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("lava_top")
world.tiles[37][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("lava_inside")
world.tiles[37][19] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[37][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("lava_top")
world.tiles[38][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("lava_inside")
world.tiles[38][19] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[38][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("snow")
world.tiles[39][19] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[39][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[40][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[41][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("static_block_dark")
world.tiles[42][16] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[42][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[43][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[44][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[45][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[46][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[47][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[48][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[49][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wooden_platform")
world.tiles[50][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wooden_platform")
world.tiles[50][16] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wooden_platform")
world.tiles[50][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[50][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wooden_platform")
world.tiles[51][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wooden_platform")
world.tiles[51][16] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wooden_platform")
world.tiles[51][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[51][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wooden_platform")
world.tiles[52][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wooden_platform")
world.tiles[52][16] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wooden_platform")
world.tiles[52][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[52][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wooden_platform")
world.tiles[53][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wooden_platform")
world.tiles[53][16] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wooden_platform")
world.tiles[53][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[53][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wooden_platform")
world.tiles[54][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wooden_platform")
world.tiles[54][16] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wooden_platform")
world.tiles[54][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[54][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wooden_platform")
world.tiles[55][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wooden_platform")
world.tiles[55][16] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wooden_platform")
world.tiles[55][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[55][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wooden_platform")
world.tiles[56][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wooden_platform")
world.tiles[56][16] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wooden_platform")
world.tiles[56][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[56][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wooden_platform")
world.tiles[57][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wooden_platform")
world.tiles[57][16] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wooden_platform")
world.tiles[57][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[57][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wooden_platform")
world.tiles[58][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wooden_platform")
world.tiles[58][16] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wooden_platform")
world.tiles[58][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[58][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wooden_platform")
world.tiles[59][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wooden_platform")
world.tiles[59][16] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wooden_platform")
world.tiles[59][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[59][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wooden_platform")
world.tiles[60][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wooden_platform")
world.tiles[60][16] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wooden_platform")
world.tiles[60][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[60][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[61][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[62][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[63][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[64][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_top")
world.tiles[65][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[65][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[65][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[65][16] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[65][17] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[65][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[65][19] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[65][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_top")
world.tiles[66][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[66][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[66][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[66][16] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[66][17] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[66][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[66][19] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[66][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_top")
world.tiles[67][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[67][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[67][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[67][16] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[67][17] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[67][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[67][19] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[67][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_top")
world.tiles[68][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[68][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[68][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[68][16] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[68][17] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[68][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[68][19] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[68][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_top")
world.tiles[69][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[69][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[69][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[69][16] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[69][17] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[69][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[69][19] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[69][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_top")
world.tiles[70][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[70][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[70][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[70][16] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[70][17] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[70][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[70][19] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[70][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_top")
world.tiles[71][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[71][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[71][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[71][16] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[71][17] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[71][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[71][19] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[71][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_top")
world.tiles[72][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[72][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[72][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[72][16] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[72][17] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[72][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[72][19] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[72][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_top")
world.tiles[73][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[73][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[73][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[73][16] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[73][17] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[73][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[73][19] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[73][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_top")
world.tiles[74][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[74][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[74][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[74][16] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[74][17] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[74][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[74][19] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[74][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_top")
world.tiles[75][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[75][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[75][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[75][16] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[75][17] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[75][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[75][19] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[75][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_top")
world.tiles[76][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[76][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[76][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[76][16] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[76][17] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[76][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[76][19] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[76][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_top")
world.tiles[77][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[77][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[77][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[77][16] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[77][17] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[77][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[77][19] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[77][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_top")
world.tiles[78][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[78][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[78][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[78][16] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[78][17] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[78][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[78][19] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[78][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_top")
world.tiles[79][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[79][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[79][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[79][16] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[79][17] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[79][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[79][19] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[79][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_top")
world.tiles[80][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[80][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[80][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[80][16] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[80][17] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[80][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[80][19] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[80][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_top")
world.tiles[81][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[81][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[81][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[81][16] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[81][17] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[81][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[81][19] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[81][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_top")
world.tiles[82][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[82][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[82][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[82][16] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[82][17] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[82][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[82][19] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[82][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_top")
world.tiles[83][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[83][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[83][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[83][16] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[83][17] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[83][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[83][19] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[83][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_top")
world.tiles[84][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[84][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[84][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[84][16] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[84][17] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[84][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[84][19] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[84][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_top")
world.tiles[85][13] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[85][14] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[85][15] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[85][16] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[85][17] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[85][18] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h3 = world.headerContainer:getHeader("water_inside")
world.tiles[85][19] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[85][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[86][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[87][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[88][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[89][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[90][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[91][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[92][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[93][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[94][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[95][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[96][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[97][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[98][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[99][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[100][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[101][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[102][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[103][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[104][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[105][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[106][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[107][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[108][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[109][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[110][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[111][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[112][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[113][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[114][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[115][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[116][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[117][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[118][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[119][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[120][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[121][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[122][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[123][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[124][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[125][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[126][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[127][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[128][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[129][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("brick_dark_coins")
world.tiles[130][19] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[130][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[131][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[132][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[133][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[134][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[135][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[136][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[137][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[138][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[139][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
h1 = world.headerContainer:getHeader("wood")
world.tiles[140][20] = Tile:new(h1, h2, h3)
h1, h2, h3 = nil, nil, nil
-- Grid end

-- Animation objects begin
world:fillObjectIntoGrid(createAnimationObjectFromName("snow_blanket", 2, 19, self.tileWidth,  self.tileHeight, self.textureContainer, self.animObjContainer), "foregroundObj")
world:fillObjectIntoGrid(createAnimationObjectFromName("snow_blanket", 3, 19, self.tileWidth,  self.tileHeight, self.textureContainer, self.animObjContainer), "foregroundObj")
world:fillObjectIntoGrid(createAnimationObjectFromName("grass_1_1", 4, 19, self.tileWidth,  self.tileHeight, self.textureContainer, self.animObjContainer), "backgroundObj")
world:fillObjectIntoGrid(createAnimationObjectFromName("torch", 22, 17, self.tileWidth,  self.tileHeight, self.textureContainer, self.animObjContainer), "backgroundObj")
-- Animation objects end

-- Active objects begin
local acObj
acObj = createActiveObjectFromName("trampoline", 4, 16, world.tileWidth, world.tileHeight, world.textureContainer, false, nil)
world:addActiveObject(acObj)
acObj = createActiveObjectFromName("teleport", 3, 16, world.tileWidth, world.tileHeight, world.textureContainer, false, nil)
world:addActiveObject(acObj)
world:connectTeleports(acObj.x, acObj.y, 40, 19)
acObj = createActiveObjectFromName("teleport", 40, 19, world.tileWidth, world.tileHeight, world.textureContainer, false, nil)
world:addActiveObject(acObj)
world:connectTeleports(acObj.x, acObj.y, 3, 16)
-- Active objects end

-- Units begin
local unit
-- Units end

-- Parallax background begin
-- Background begin: 1
world:setBackgroundTexture(1, "background1_day")
world:setCameraVelocityParallaxBackground(1, 0)
-- Background end
-- Background begin: 2
world:setBackgroundTexture(2, "background2_snow_mountains")
world:enableWeather(2, Clouds, nil, 3)
world:setCameraVelocityParallaxBackground(2, 0.05)
-- Background end
-- Background begin: 3
world:setBackgroundTexture(3, "background3_spring_forest")
world:enableWeather(3, Clouds, nil, 10)
world:setCameraVelocityParallaxBackground(3, 0.2)
-- Background end
-- Background begin: 4
world:enableWeather(4, Snow, true)
world:enableWeather(4, Rain, false)
world:setCameraVelocityParallaxBackground(4, 0.3)
-- Background end
-- Parallax background end

-- Player spawn position begin
world.playerSpawnX = 90
world.playerSpawnY = 90
-- Player spawn position end

-- Player finish line begin
world.playerFinishLine = 8850
-- Player finish line end

end
